crud/urls.py
from django.urls import path
from . import views

app_name = "crud"

urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.new, name="new"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("edit/<int:pk>", views.edit, name="edit"),
    path("update/<int:pk>", views.update, name="update"),
]

pair/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("crud.urls")),
]

crud/models.py
from django.db import models

# Create your models here.


class Review(models.Model):
    title = models.CharField(max_length=80,null=False,blank=False)
    content = models.TextField(default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

crud/views.py
from turtle import title
from django.shortcuts import render, redirect
from .models import Review

# Create your views here.


def index(request):
    reviews = Review.objects.all()
    context = {
        "reviews": reviews,
    }
    return render(request, "crud/index.html", context)


def new(request):
    return render(request, "crud/new.html")


def create(request):
    content = request.GET.get("content")
    title = request.GET.get("title")

    if title == '' :
        title = 'Secret'
    if content =='':
        content = 'I don\'t remember, but I want to write a review'

    print(title)
    print(content)
    
    Review.objects.create(
        content=content,
        title=title,
    )

  
    return redirect("crud:index")


def detail(request, pk):
    review = Review.objects.get(pk=pk)
    context = {
        "review": review,
    }
    return render(request, "crud/detail.html", context)


def delete(request, pk):
    review = Review.objects.get(pk=pk)
    review.delete()

    return redirect("crud:index")


def edit(request, pk):

    review = Review.objects.get(pk=pk)

    context = {
        "review": review,
    }

    return render(request, "crud/edit.html", context)


def update(request, pk):
    # update할 특정 데이터를 불러온다. -> todo_pk 를 사용해서
    review = Review.objects.get(pk=pk)

    content_ = request.GET.get("content")
    title_ = request.GET.get("title")

    review.content = content_
    review.title = title_

    review.save()

    return redirect("crud:index")

crud/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=IM+Fell+English&family=Noto+Sans+KR:wght@300&display=swap"
      rel="stylesheet"
    />
    <style>
      body {
        font-family: 'IM Fell English', serif;
        /* font-family: 'Noto Sans KR', sans-serif; */
      }
      @import url('https://fonts.googleapis.com/css2?family=IM+Fell+English&display=swap');
      /* body {
        background-image: ;
        background-repeat: no-repeat;
        background-size: cover; */

      /* background-color:#000; */
      /* } */

      .container11 {
        width: 100%;
        height: 100vw;
        text-align: center;
        position: relative;
        z-index: 1;
        background-repeat: no-repeat;
        background-size: cover;
      }
      .container11::after {
        width: 100%;
        height: 100vw;
        content: '';
        background: url('http://joyposter.cafe24.com//NEW-posters/F600X848Poster/SMS-006.jpg');
        position: absolute;
        top: 0;
        left: 0;
        z-index: -1;
        opacity: 0.5;
        background-size: cover;
        background-repeat: no-repeat;
      }
    </style>
  </head>

  <body class="">
    <container class="container11">
      {% block content %} {% endblock %}
    </container>
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

crud/templates/crud/detail.html
{% extends 'base.html' %} {% block content %}

      
    
    

  <div class="container pt-5">
    <h1 class="text-center mb-3">REVIEW</h1>
    <form action="{% url 'crud:create' %}">
      <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">
            TITLE
        </label>
        <input name="title" readonly type="text" class="form-control" maxlength="10" value="{{ review.title }}" />
      </div>
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">
            CONTENT
        </label>
        <textarea type="text" name="content" class="form-control" readonly > {{ review.content }}</textarea>
      </div>
      <div class="d-grid gap-2">
        <a class="btn btn-outline-primary" href="{% url 'crud:edit' review.pk %}">
            UPDATE
          </a>
          <a class="btn btn-outline-danger" href="{% url 'crud:delete' review.pk%}">
            DELETE
          </a>
        
      </div>
    </form>
  </div>

  {% endblock%}
</div>

crud/templates/crud/edit.html
{% extends 'base.html' %} {% block content %}


<div class="container pt-5">
  <h1 class="text-center mb-3">REVIEW EDIT</h1>
  <form action="{% url 'crud:update' review.pk %}">
    <div class="mb-3">
      <label for="exampleFormControlInput1" class="form-label">
        TITLE
      </label>
      <input name="title" type="text" class="form-control" maxlength="10" value="{{ review.title }}" />
    </div>
    <div class="mb-3">
      <label for="exampleFormControlTextarea1" class="form-label">
        CONTENT
      </label>
      <textarea type="text" name="content" class="form-control">{{ review.content }}</textarea>
    </div>
    <div class="d-grid gap-2">
      <input class="btn btn-outline-primary" type="submit" value="EDIT"></input>
      <a type="button" class="btn btn-outline-dark px-5" href="{% url 'crud:index' %}"><span class="fw-bold">BACK</span></a>
    </div>
  </form>
  
</div>
{% endblock%}

crud/templates/crud/index.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <h1 class="text-center pt-5">MOVIE REVIEW</h1>
  <div class="p-3 d-flex justify-content-end">
    <a class="btn btn-dark text-decoration-none" href="{% url 'crud:new' %}">
      Create
    </a>
  </div>
  <div class="p-3">
    <table class="table text-center table-borderless">
      <thead>
        <tr class="table-dark">
          <th scope="col">No.</th>
          <th scope="col">Title</th>
          <th scope="col">Edit</th>
        </tr>
      </thead>
      <tbody>
        {% for review in reviews %}
        <tr class="table-light opacity-50 fw-bold">
          <th scope="row">{{ forloop.counter }}</th>
          <td>
            <a
              class="text-decoration-none text-dark"
              href="{% url 'crud:detail' review.pk %}"
            >
              {{review.title}}
            </a>
          </td>
          <td class="text-dark">
            {{ review.updated_at.year }}.{{ review.updated_at.month }}.
            {{review.updated_at.day }} - {{review.updated_at.hour}} :
            {{review.updated_at.minute}}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock%}

crud/templates/crud/new.html
{% extends 'base.html' %}
{% block content %}

  <div class="container pt-5">
    <h1 class="text-center mb-3">REVIEW CREATE</h1>
    <form action="{% url 'crud:create' %}">
      <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">
          TITLE
        </label>
        <input name="title" type="text" class="form-control " maxlength="10" required="required"/>
      </div>
      <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">
          CONTENT
        </label>
        <textarea type="text" name="content" class="form-control  " required="required"></textarea>
      </div>
      <div class="d-grid gap-2">
        <input class="btn btn-outline-primary" type="submit" value="Create"></input>
      </div>
    </form>
  </div>

  {% endblock%}

crud/templates/index.html
123,37,32,101,120,116,101,110,100,115,32,39,98,97,115,101,46,104,116,109,108,39,32,37,125,32,123,37,32,98,108,111,99,107,32,99,111,110,116,101,110,116,32,37,125,10,60,97,32,104,114,101,102,61,34,34,62,235,141,148,235,179,180,234,184,176,60,47,97,62,10,123,37,32,101,110,100,98,108,111,99,107,37,125,10